name: Feature PR

on:
  pull_request:
    branches:
      - 'feature/*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          sudo ./sfdx-cli/install

      - name: Install sfdx scanner plugin
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: Install jq
        run: |
          sudo apt-get install jq
      
      - name: Run security scan
        run: |
          sfdx scanner:run -a scan_results.json -o json -f force-app/main/default -d 5 -m "ApexClass,ApexTrigger,ApexPage,ApexComponent" -r "High,Medium"

      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: scan-results
          path: scan_results_${{ github.sha }}.json
